# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # This should match the latest stable version
    hooks:
      - id: black
        args: ["--line-length=88"]  # Ensure the line-length is set appropriately

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Version of isort
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=88"]  # Align with black