"""Implement User registration and authentication

Revision ID: 2868b34bd4ab
Revises: 6872e9aadae0
Create Date: 2024-10-02 23:23:37.429493

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2868b34bd4ab"
down_revision: Union[str, None] = "6872e9aadae0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
